sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

language: scala

jdk:
  - oraclejdk8
  - openjdk7

script:
  - sbt ";++$TRAVIS_SCALA_VERSION;$SBT_COMMAND"

before_cache:
  - find $HOME/.sbt -name '*.lock' | xargs rm
  - find $HOME/.ivy2 -name 'ivydata-*.properties' | xargs rm

env:
  matrix:
    - SBT_COMMAND=test

before_deploy:
  - travis_retry git clone --depth=1 $secret_git ./secret

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    condition: -e ./deploy.sh
    all_branches: true
    jdk: openjdk7
