sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

language: scala

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

script:
  - sbt ";++$TRAVIS_SCALA_VERSION;$SBT_COMMAND"

before_cache:
  - find $HOME/.sbt -name '*.lock' | xargs rm
  - find $HOME/.ivy2 -name 'ivydata-*.properties' | xargs rm
